# Manipulating Arrays

Here are two techniques that can be used to change or manipulayte the structure of arrays:
*  Stacking
*  Reshaping

### Stacking

What if we want to perform concatenation or merging activity on numpy arrays like list. This activity in numpy arrays is called as ```stacking```.

There are two types of stacking 
1. Horizontal stacking
2. Vertical stacking

Stacking is done using the ```np.hstack()``` and ```np.vstack()``` methods. 

For horizontal stacking, the number of rows should be the same, while for vertical stacking, the number of columns should be the same. 

In [1]:
#importing the NumPy library
import numpy as np

# Creating two 1-D arrays with 5 elements using arange
arr_1 = np.arange(5)
arr_2 = np.arange(5, 10)


In [4]:
# Horizonal stacking - Appending the elements in the same row
np.hstack((arr_1,arr_2))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Vertical stacking - Increasing the number of row
arr_3 = np.vstack((arr_1,arr_2))

# Storing the stacked array for further operations
arr_3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
# Checking the dimensions of the array
arr_3.ndim

2

In [7]:
# Number of rows and columns in the array
arr_3.shape

(2, 5)

### Reshaping

Another manipulation that is performed over arrays is reshaping. It is done using the ```reshape()``` function. It helps you to change the dimensions of the existing arrays.

In [8]:
# Creating an array of first ten natural numbers
arr_4 = np.arange(1,11)

# Printing the created array
arr_4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# Reshaping the 1D array into a 2D array with 2 elements in five rows
arr_5 = arr_4.reshape(5,2)

In [10]:
# Checking the rows and columns in the created array
arr_5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [11]:
arr_5.shape

(5, 2)

In [13]:
# Creating a 2D array with 4 elements in five rows (elements from 20 to 39)
arr_6 = np.arange(20,40).reshape(5,4)

# Checking the rows and columns in the created array
arr_6

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [15]:
# Stacking arr_5 and arr_6
np.vstack((arr_5,arr_6))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 4

The reason behind is the shape because it is different. Here we should be careful that columns should be same.

In [16]:
# Check the structure of arr_6
arr_6.shape

(5, 4)

In [22]:
# Reshape the arr_6 to vertically stack with arr_5 
arr_6 = np.arange(20,40).reshape(10,2)
arr_6

array([[20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [20]:
arr_6.shape

(10, 2)

In [23]:
# Stacking arr_5 and arr_6
np.vstack((arr_5, arr_6))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

Questions

1. Index of the 100th Element
Consider an (11,12) shape array. What is the index (x,y) of the 100th element? Note: For counting the elements, go row-wise. For example, in the array:

[[1, 5, 9],
 [3, 0, 2]]
the 5th element would be '0'.

Answer: 
(8, 3)


Feedback:
You can create an 11 x 12 array using np.array(range(1, 11*12+1)). You can reshape it to an (11 x 12) array and then check the position of 100. Be clear that the indexing starts from 0; hence, the 9th row will have the index 8.
Alternatively, you can also use np.unravel_index(99, (11,12)) on the created array.

2. Reshaping an Array
Consider the array provided below: 


    [[1, 2, 3, 4, 5]
     [6, 7, 8, 9, 10]
     [11, 12, 13, 14, 15]
     [16, 17, 18, 19, 20]]
     
Now, you are expected to generate the following array out of it:

    [[1, 3]
     [5, 7]
     [9, 11]
     [13, 15]
     [17, 19]]
     
Which code will give you the correct output?
(Hint: Also check if one or more options are correct.)


rint(array_1[array_1%2 != 0].reshape(5, 2))
✓ Correct
Feedback:
print(array_1[array_1%2 != 0].reshape(5, 2))
This is the correct way to slice odd entries and arrange them in the given order.